name: EX – Prep task
description: A preparatory task without direct user value
title: "[Prep] <title>"
labels: ["App: ElementX Android", "App: ElementX iOS", "T-Prep", "Team: Element X Platform"]

body:
- type: textarea
  attributes:
    label: Description
    value: |
      Description of the task

      # Acceptance criteria
      - TBD

      # Size estimate
      S/M/L
      
      # Dependencies    
      - None
      
      # Out of scope
      - 
      
      # Subtasks
      ```[tasklist]
      ### Android
      ```
      
      ```[tasklist]
      ### iOS
      ```

      ```[tasklist]
      ### Rust
      ```
      
      ```[tasklist]
      ### Other
      ```
  validations:
    required: false
