name: EX – Prep task
description: A preparatory task without direct user value
title: "[Prep] <title>"
labels: ["App: ElementX Android", "App: ElementX iOS", "T-Prep", "Team: Element X Platform"]

body:
- type: textarea
  attributes:
    label: Description
    value: |
      Description of the task

      # Acceptance criteria
      - TBD

      # Size estimate
      S/M/L
      
      # Dependencies    
      - None
      
      # Out of scope
      - 
      
      # Subtasks
      Subtasks should be created as separate GitHub issues in the corresponding platform repositories.
      Add them as sub-issues of this prep task.  
      (Optional) You may also list them below as checklist items for quick visibility.
  
      ### Android
      -
      
      ### iOS
      -
      
      ### Rust
      -
   
      ### Other
      -
  
  validations:
    required: false
