name: EX – User story
description: Template for a second-level planning issue template. It must be part of an Epic.
title: "[Story] <title>"
labels: ["App: ElementX Android", "App: ElementX iOS", "T-User Story", "Team: Element X Platform"]

body:
- type: textarea
  attributes:
    label: Description
    value: |
      * As a [beneficiary]
      * I want to [objective]
      * So that [value generated]

      # Acceptance criteria
      - TBD

      # Dependencies
      - None

      # Out of scope
      - Nothing

      # Questions
      - [x] None

      # Subtasks
      Subtasks should be created as separate GitHub issues in the corresponding platform repositories.
      Add them as sub-issues of this user story.
      (Optional) You may also list them below as checklist items for quick visibility.

      ### Android
      -
      
      ### iOS
      -
      
      ### Rust
      -

      ### Other
      -
