name: EX – User story
description: Template for a second-level planning issue template. It must be part of an Epic.
title: "[Story] <title>"
labels: ["App: ElementX Android", "App: ElementX iOS", "T-User Story", "Team: Element X Platform"]

body:
- type: textarea
  attributes:
    label: Description
    value: |
      * As a [beneficiary]
      * I want to [objective]
      * So that [value generated]
- type: textarea
  attributes:
    label: Acceptance criteria
    value: |
      - TBD
- type: dropdown
  attributes:
    label: Size estimate
    options:
      - S
      - M
      - L
- type: textarea
  attributes:
    label: Dependencies
    value: |
      - None
- type: textarea
  attributes:
    label: Out of scope
    value: |
      - Nothing
- type: textarea
  attributes:
    label: Open questions
    value: |
      ```[tasklist]
      ### Questions
      ```
- type: textarea
  attributes:
    label: Subtasks
    value: |
      ```[tasklist]
      ### Android
      ```
      
      ```[tasklist]
      ### iOS
      ```
      
      ```[tasklist]
      ### Rust
      ```

      ```[tasklist]
      ### Other
      ```
