name: User story
description: Second-level planning issue template. A story should take about a week or a sprint to finish. It is normally one of a number of parts of an Epic
title: "[Story] <title>"
labels: [T-User Story]

body:
- type: textarea
  attributes:
    label: Story
    description: A story should take roughly a week or a sprint to finish. Each story is usually made up of a number of tasks that take half to a full day.
    value: |
      As a user…
      I want to…
      so that I can…
- type: textarea
  attributes:
    label: Dependencies
    value: |
      - TBD
- type: textarea
  attributes:
    label: Sign-offs
    value: |
      #### Android
      - [ ] Design sign-off on completion
      - [ ] QA sign-off on completion
      - [ ] Product sign-off on completion

      #### iOS
      - [ ] Design sign-off on completion
      - [ ] QA sign-off on completion
      - [ ] Product sign-off on completion

      #### Web
      - [ ] Design sign-off on completion
      - [ ] QA sign-off on completion
      - [ ] Product sign-off on completion
- type: textarea
  attributes:
    label: Scope
    value: |
      <!--These should be a list of technical tasks which take ½-1 day to complete-->
      ```[tasklist]
      ### Android
      - [ ] Verified with build in screen reader
      ```

      ```[tasklist]
      ### iOS
      - [ ] Verified with build in screen reader
      ```

      ```[tasklist]
      ### Web
      - [ ] Verified with system in screen reader
      ```
      
      ## Out of scope
      <!-- Include known issues here, as well as anything that has been acknowledged as not in the scope of this story -->
      - TBD
      
  validations:
    required: false
