name: X-Plorers – User story
description: A task that generates direct user value
title: "[Story] ..."
labels: ["App: ElementX Android", "App: ElementX iOS", "T-User Story", "Team: Element X Feature"]

body:
- type: textarea
  attributes:
    label: Description
    value: |
      * As a [beneficiary]
      * I want to [objective]
      * So that [value generated]
- type: textarea
  attributes:
    label: Acceptance criteria
    value: |
      - TBD
- type: dropdown
  attributes:
    label: Size estimate
    options:
      - S
      - M
      - L
- type: textarea
  attributes:
    label: Dependencies
    value: |
      - TBD
- type: textarea
  attributes:
    label: Preconditions
    value: |
      - TBD
- type: textarea
  attributes:
    label: Out of scope
    value: |
      - TBD
- type: textarea
  attributes:
    label: Open questions
    value: |
      - TBD
- type: textarea
  attributes:
    label: Subtasks
    value: |
      ```[tasklist]
      ### Android
      ```
      
      ```[tasklist]
      ### iOS
      ```
      
      ```[tasklist]
      ### Other
      ```
