name: Static Analysis
on:
    pull_request: {}
    push:
        branches: [develop]
jobs:
    workflow_lint:
        name: "Workflow Lint"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  cache: "yarn"

            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Run Linter
              run: "yarn lint:workflows"
