name: Sync labels
on:
  workflow_dispatch: {}
  # Disabled for now while we're testing
  # push:
  #   branches:
  #     - develop
  #   paths:
  #     - .github/labels.yml
  workflow_call:
    inputs:
      LABELS:
        description: |
          List of label sources, one per line. Sources can either be GitHub repository
          slugs or paths to local YAML files in the format specified in
          https://github.com/Financial-Times/github-label-sync#label-config-file".
          The sources will merge/override each other in the order they were specified in.
        type: string
        default: |
          .github/labels.yml
        required: true
      DELETE:
        description: |
          Remove labels that exist in the repository but are missing from all sources
        type: boolean
        default: false
      WET:
        description: |
          Write changes, *don't* run in dry mode
        type: boolean
        default: false
    secrets:
      ELEMENT_BOT_TOKEN:
        description: Sufficiently privileged GitHub token
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out calling repository
        uses: actions/checkout@v4
        if: github.repository != 'vector-im/element-meta'
      - name: Check out vector-im/element-meta
        uses: actions/checkout@v4
        with:
          path: element-meta
          repository: vector-im/element-meta
      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: element-meta/yarn.lock
      - name: Install Deps
        run: "yarn install --frozen-lockfile"
      - name: "Sync labels"
        run: |
          yarn sync-labels $(echo -e "${{ inputs.LABELS }}" | xargs -r printf -- '--labels \"%s\"\n' | xargs echo) \
            ${{ github.repository != 'vector-im/element-meta' && '--dir ..' }} \
            ${{ inputs.DELETE && '--delete' }} \
            ${{ inputs.WET && '--wet' }}
        working-directory: element-meta
        env:
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
