name: Sync labels
on:
  workflow_dispatch: {}
  # Disabled for now while we're testing
  # push:
  #   branches:
  #     - develop
  #   paths:
  #     - .github/labels.yml
  workflow_call:
    inputs:
      LABELS:
        description: |
          List of label sources, one per line. Sources can either be GitHub repository
          slugs or paths to local YAML files in the format specified in
          https://github.com/Financial-Times/github-label-sync#label-config-file".
          The sources will merge/override each other in the order they were specified in.
        type: string
        default: |
          .github/labels.yml
        required: true
      DELETE:
        description: |
          Remove labels that exist in the repository but are missing from all sources
        type: boolean
        default: false
      WET:
        description: |
          Write changes, *don't* run in dry mode
        type: boolean
        default: false
    secrets:
      ELEMENT_BOT_TOKEN:
        description: Sufficiently privileged GitHub token
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out element-hq/element-meta
        uses: actions/checkout@v4
        with:
          repository: element-hq/element-meta

      # nb. this put the caller repo within the element-meta checkout so it must
      # be done afterwards as actions/checkout erases the directory
      - name: Check out calling repository
        uses: actions/checkout@v4
        if: github.repository != 'element-hq/element-meta'
        with:
          path: caller-repository

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install Deps
        run: "yarn install --frozen-lockfile"

      - name: "Sync labels"
        run: |
          yarn sync-labels $(echo -e "${{ inputs.LABELS }}" | xargs -r printf -- '--labels \"%s\"\n' | xargs echo) \
            ${{ github.repository != 'element-hq/element-meta' && '--dir ./caller-repository' }} \
            ${{ inputs.DELETE && '--delete' }} \
            ${{ inputs.WET && '--wet' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
