name: Move labelled issues to correct boards and columns

on:
  issues:
    types: [labeled]

jobs:

  ex_platform:
    name: Add labelled issues to EX platform project
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Team: Element X Platform')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/43
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  voip:
    name: Add labelled issues to VoIP project board
    runs-on: ubuntu-latest
    if: >
      contains(github.event.issue.labels.*.name, 'Team: VoIP')
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/element-hq/projects/139
          github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
