name: Move unlabelled from needs info columns to triaged

on:
  issues:
    types: [unlabeled]

jobs:
  remove_Z-Labs_label:
    name: Remove Z-Labs label when features behind labs flags are removed
    runs-on: ubuntu-latest
    if: >
        !(contains(github.event.issue.labels.*.name, 'A-Maths') ||
        contains(github.event.issue.labels.*.name, 'A-Message-Pinning') ||
        contains(github.event.issue.labels.*.name, 'A-Threads') ||
        contains(github.event.issue.labels.*.name, 'A-Polls') ||
        contains(github.event.issue.labels.*.name, 'A-Location-Sharing') ||
        contains(github.event.issue.labels.*.name, 'A-Message-Bubbles') ||
        contains(github.event.issue.labels.*.name, 'Z-IA') ||
        contains(github.event.issue.labels.*.name, 'A-Themes-Custom') ||
        contains(github.event.issue.labels.*.name, 'A-E2EE-Dehydration') ||
        contains(github.event.issue.labels.*.name, 'A-Tags')) &&
        contains(github.event.issue.labels.*.name, 'Z-Labs')
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['Z-Labs']
            })
